HW 5. `cd` & `ls`
vladnosiv/sd-hse-2022 pull request #39
Opened 2022-03-03 10:47 UTC by kibrq

2022-03-03 10:49 UTC, kibrq commented
Пока workflow можно не запускать. Сделаны только тесты

2022-03-07 18:43 UTC, kibrq commented
Пускайте воркфлоу

2022-03-08 19:07 UTC, yurii-litvinov requested changes
- падает на `ls имя-файла`
- `cd` без параметра вроде как ничего не делает, а должна переходить в домашнюю папку текущего пользователя
- `cd` не согласована с внешними командами, например, `cd ..` и `git status` выдаст статус репозитория, хотя по идее мы не в нём
- С абсолютными путями под виндой некоторая беда, переход `cd C:/Users` не работает, зато работает `cd /Users`

2022-03-08 19:07 UTC, yurii-litvinov commented on ast_walker/functions.py
> +def shell_cd(input_stream, *args):
Что-то совсем комментариев нет. У товарищей хоть и не в Docstring, но хоть как-то.

2022-03-08 19:07 UTC, yurii-litvinov commented on ast_walker/test/test_cd.py
> +def test_unexisting_path(tmp_path):
unexisting — это типа как undead? :) nonexistent грамматически более правильно

2022-03-08 19:07 UTC, yurii-litvinov commented on review.md
> +* идентация то табы, то пробелы(даже внутри одного файла)
```suggestion
* идентация то табы, то пробелы (даже внутри одного файла)
```
Но вообще да, в наши времена за такое сразу незачёт был

2022-03-08 19:07 UTC, yurii-litvinov commented on review.md
> +* долго пытался понять, почему не работает интеграционный тест, оказалось, что `grep` забивает на переданный `IO` и протсо делает `print()` результата на экран
```suggestion
* долго пытался понять, почему не работает интеграционный тест, оказалось, что `grep` забивает на переданный `IO` и просто делает `print()` результата на экран
```

2022-03-14 15:49 UTC, maxuh14 commented on ast_walker/functions.py
> +def shell_cd(input_stream, *args):
fixed

2022-03-14 15:49 UTC, maxuh14 commented on ast_walker/test/test_cd.py
> +def test_unexisting_path(tmp_path):
fixed

2022-03-14 20:05 UTC, kibrq commented
> * С абсолютными путями под виндой некоторая беда, переход `cd C:/Users` не работает, зато работает `cd /Users`

Так на виндовсе C:\Users. Или так тоже не работает?

2022-06-18 10:45 UTC, yurii-litvinov commented
В виндовсе должно работать и так и так. У вас же не работает никак, парсер агрится на `:`. Но всё остальное теперь работает, так что зачтена.

2022-08-21 20:09 UTC, closed without merging